services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping_lists_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data

  shopping-list-app:
    build: .
    ports:
      - "8989:8989"

volumes:
  mongodb_data:
  redis_data:
  postgres_data:
