// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/grpc/v1/shopping_list.proto

package shopping_list_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_DONT_USE State = 0
	State_STATE_ARCHIVED State = 1
	State_STATE_ACTIVE   State = 2
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_DONT_USE",
		1: "STATE_ARCHIVED",
		2: "STATE_ACTIVE",
	}
	State_value = map[string]int32{
		"STATE_DONT_USE": 0,
		"STATE_ARCHIVED": 1,
		"STATE_ACTIVE":   2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_v1_shopping_list_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_api_grpc_v1_shopping_list_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{0}
}

type ShoppingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Items         []string               `protobuf:"bytes,8,rep,name=Items,proto3" json:"Items,omitempty"`
	State         State                  `protobuf:"varint,9,opt,name=state,proto3,enum=shopping_list.v1.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingList) Reset() {
	*x = ShoppingList{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingList) ProtoMessage() {}

func (x *ShoppingList) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingList.ProtoReflect.Descriptor instead.
func (*ShoppingList) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{0}
}

func (x *ShoppingList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShoppingList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShoppingList) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShoppingList) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShoppingList) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ShoppingList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShoppingList) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_DONT_USE
}

type Item struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Comment        string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsDone         bool                   `protobuf:"varint,4,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	UserId         string                 `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ShoppingListId string                 `protobuf:"bytes,8,opt,name=ShoppingListId,proto3" json:"ShoppingListId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Item) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *Item) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Item) GetShoppingListId() string {
	if x != nil {
		return x.ShoppingListId
	}
	return ""
}

type CreateShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Items         []string               `protobuf:"bytes,8,rep,name=Items,proto3" json:"Items,omitempty"`
	State         State                  `protobuf:"varint,9,opt,name=state,proto3,enum=shopping_list.v1.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShoppingListRequest) Reset() {
	*x = CreateShoppingListRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingListRequest) ProtoMessage() {}

func (x *CreateShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingListRequest.ProtoReflect.Descriptor instead.
func (*CreateShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateShoppingListRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateShoppingListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShoppingListRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateShoppingListRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CreateShoppingListRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateShoppingListRequest) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_DONT_USE
}

type CreateShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShoppingList  *ShoppingList          `protobuf:"bytes,1,opt,name=shoppingList,proto3" json:"shoppingList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShoppingListResponse) Reset() {
	*x = CreateShoppingListResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingListResponse) ProtoMessage() {}

func (x *CreateShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingListResponse.ProtoReflect.Descriptor instead.
func (*CreateShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShoppingListResponse) GetShoppingList() *ShoppingList {
	if x != nil {
		return x.ShoppingList
	}
	return nil
}

type UpdateShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Items         []string               `protobuf:"bytes,8,rep,name=Items,proto3" json:"Items,omitempty"`
	State         State                  `protobuf:"varint,9,opt,name=state,proto3,enum=shopping_list.v1.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShoppingListRequest) Reset() {
	*x = UpdateShoppingListRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShoppingListRequest) ProtoMessage() {}

func (x *UpdateShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShoppingListRequest.ProtoReflect.Descriptor instead.
func (*UpdateShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateShoppingListRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateShoppingListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateShoppingListRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateShoppingListRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateShoppingListRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateShoppingListRequest) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_DONT_USE
}

type UpdateShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShoppingList  *ShoppingList          `protobuf:"bytes,1,opt,name=shoppingList,proto3" json:"shoppingList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShoppingListResponse) Reset() {
	*x = UpdateShoppingListResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShoppingListResponse) ProtoMessage() {}

func (x *UpdateShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShoppingListResponse.ProtoReflect.Descriptor instead.
func (*UpdateShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateShoppingListResponse) GetShoppingList() *ShoppingList {
	if x != nil {
		return x.ShoppingList
	}
	return nil
}

type DeleteShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShoppingListRequest) Reset() {
	*x = DeleteShoppingListRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShoppingListRequest) ProtoMessage() {}

func (x *DeleteShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShoppingListRequest.ProtoReflect.Descriptor instead.
func (*DeleteShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShoppingListResponse) Reset() {
	*x = DeleteShoppingListResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShoppingListResponse) ProtoMessage() {}

func (x *DeleteShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShoppingListResponse.ProtoReflect.Descriptor instead.
func (*DeleteShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{7}
}

type GetShoppingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShoppingListRequest) Reset() {
	*x = GetShoppingListRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShoppingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingListRequest) ProtoMessage() {}

func (x *GetShoppingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingListRequest.ProtoReflect.Descriptor instead.
func (*GetShoppingListRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{8}
}

func (x *GetShoppingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShoppingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShoppingList  *ShoppingList          `protobuf:"bytes,1,opt,name=shoppingList,proto3" json:"shoppingList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShoppingListResponse) Reset() {
	*x = GetShoppingListResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShoppingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingListResponse) ProtoMessage() {}

func (x *GetShoppingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingListResponse.ProtoReflect.Descriptor instead.
func (*GetShoppingListResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{9}
}

func (x *GetShoppingListResponse) GetShoppingList() *ShoppingList {
	if x != nil {
		return x.ShoppingList
	}
	return nil
}

type GetShoppingListsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShoppingList  []*ShoppingList        `protobuf:"bytes,1,rep,name=shoppingList,proto3" json:"shoppingList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShoppingListsResponse) Reset() {
	*x = GetShoppingListsResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShoppingListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingListsResponse) ProtoMessage() {}

func (x *GetShoppingListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingListsResponse.ProtoReflect.Descriptor instead.
func (*GetShoppingListsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{10}
}

func (x *GetShoppingListsResponse) GetShoppingList() []*ShoppingList {
	if x != nil {
		return x.ShoppingList
	}
	return nil
}

type CreateItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Comment        string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsDone         bool                   `protobuf:"varint,4,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	UserId         string                 `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ShoppingListId string                 `protobuf:"bytes,8,opt,name=ShoppingListId,proto3" json:"ShoppingListId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{11}
}

func (x *CreateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateItemRequest) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *CreateItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateItemRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateItemRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CreateItemRequest) GetShoppingListId() string {
	if x != nil {
		return x.ShoppingListId
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{12}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Comment        string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsDone         bool                   `protobuf:"varint,4,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	UserId         string                 `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ShoppingListId string                 `protobuf:"bytes,8,opt,name=ShoppingListId,proto3" json:"ShoppingListId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateItemRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UpdateItemRequest) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *UpdateItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateItemRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateItemRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateItemRequest) GetShoppingListId() string {
	if x != nil {
		return x.ShoppingListId
	}
	return ""
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{16}
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{17}
}

func (x *GetItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{18}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{19}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetItemsByShoppingListIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsByShoppingListIdResponse) Reset() {
	*x = GetItemsByShoppingListIdResponse{}
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsByShoppingListIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsByShoppingListIdResponse) ProtoMessage() {}

func (x *GetItemsByShoppingListIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_shopping_list_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsByShoppingListIdResponse.ProtoReflect.Descriptor instead.
func (*GetItemsByShoppingListIdResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_shopping_list_proto_rawDescGZIP(), []int{20}
}

func (x *GetItemsByShoppingListIdResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_grpc_v1_shopping_list_proto protoreflect.FileDescriptor

const file_api_grpc_v1_shopping_list_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/grpc/v1/shopping_list.proto\x12\x10shopping_list.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\fShoppingList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x16\n" +
	"\x06UserId\x18\x05 \x01(\tR\x06UserId\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x14\n" +
	"\x05Items\x18\b \x03(\tR\x05Items\x12-\n" +
	"\x05state\x18\t \x01(\x0e2\x17.shopping_list.v1.StateR\x05state\"\x92\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\x12\x16\n" +
	"\x06IsDone\x18\x04 \x01(\bR\x06IsDone\x12\x16\n" +
	"\x06UserId\x18\x05 \x01(\tR\x06UserId\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12&\n" +
	"\x0eShoppingListId\x18\b \x01(\tR\x0eShoppingListId\"\x92\x02\n" +
	"\x19CreateShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\tR\x06UserId\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x14\n" +
	"\x05Items\x18\b \x03(\tR\x05Items\x12-\n" +
	"\x05state\x18\t \x01(\x0e2\x17.shopping_list.v1.StateR\x05state\"`\n" +
	"\x1aCreateShoppingListResponse\x12B\n" +
	"\fshoppingList\x18\x01 \x01(\v2\x1e.shopping_list.v1.ShoppingListR\fshoppingList\"\x92\x02\n" +
	"\x19UpdateShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\tR\x06UserId\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x14\n" +
	"\x05Items\x18\b \x03(\tR\x05Items\x12-\n" +
	"\x05state\x18\t \x01(\x0e2\x17.shopping_list.v1.StateR\x05state\"`\n" +
	"\x1aUpdateShoppingListResponse\x12B\n" +
	"\fshoppingList\x18\x01 \x01(\v2\x1e.shopping_list.v1.ShoppingListR\fshoppingList\"+\n" +
	"\x19DeleteShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\x1aDeleteShoppingListResponse\"(\n" +
	"\x16GetShoppingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x17GetShoppingListResponse\x12B\n" +
	"\fshoppingList\x18\x01 \x01(\v2\x1e.shopping_list.v1.ShoppingListR\fshoppingList\"^\n" +
	"\x18GetShoppingListsResponse\x12B\n" +
	"\fshoppingList\x18\x01 \x03(\v2\x1e.shopping_list.v1.ShoppingListR\fshoppingList\"\x9f\x02\n" +
	"\x11CreateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\x12\x16\n" +
	"\x06IsDone\x18\x04 \x01(\bR\x06IsDone\x12\x16\n" +
	"\x06UserId\x18\x05 \x01(\tR\x06UserId\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12&\n" +
	"\x0eShoppingListId\x18\b \x01(\tR\x0eShoppingListId\"@\n" +
	"\x12CreateItemResponse\x12*\n" +
	"\x04item\x18\x01 \x01(\v2\x16.shopping_list.v1.ItemR\x04item\"\x9f\x02\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\x12\x16\n" +
	"\x06IsDone\x18\x04 \x01(\bR\x06IsDone\x12\x16\n" +
	"\x06UserId\x18\x05 \x01(\tR\x06UserId\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12&\n" +
	"\x0eShoppingListId\x18\b \x01(\tR\x0eShoppingListId\"@\n" +
	"\x12UpdateItemResponse\x12*\n" +
	"\x04item\x18\x01 \x01(\v2\x16.shopping_list.v1.ItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteItemResponse\"@\n" +
	"\x10GetItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.shopping_list.v1.ItemR\x05items\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x0fGetItemResponse\x12*\n" +
	"\x04item\x18\x01 \x01(\v2\x16.shopping_list.v1.ItemR\x04item\"P\n" +
	" GetItemsByShoppingListIdResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.shopping_list.v1.ItemR\x05items*A\n" +
	"\x05State\x12\x12\n" +
	"\x0eSTATE_DONT_USE\x10\x00\x12\x12\n" +
	"\x0eSTATE_ARCHIVED\x10\x01\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x022\xb3\b\n" +
	"\x13ShoppingListService\x12N\n" +
	"\aGetItem\x12 .shopping_list.v1.GetItemRequest\x1a!.shopping_list.v1.GetItemResponse\x12F\n" +
	"\bGetItems\x12\x16.google.protobuf.Empty\x1a\".shopping_list.v1.GetItemsResponse\x12W\n" +
	"\n" +
	"CreateItem\x12#.shopping_list.v1.CreateItemRequest\x1a$.shopping_list.v1.CreateItemResponse\x12W\n" +
	"\n" +
	"UpdateItem\x12#.shopping_list.v1.UpdateItemRequest\x1a$.shopping_list.v1.UpdateItemResponse\x12W\n" +
	"\n" +
	"DeleteItem\x12#.shopping_list.v1.DeleteItemRequest\x1a$.shopping_list.v1.DeleteItemResponse\x12f\n" +
	"\x0fGetShoppingList\x12(.shopping_list.v1.GetShoppingListRequest\x1a).shopping_list.v1.GetShoppingListResponse\x12V\n" +
	"\x10GetShoppingLists\x12\x16.google.protobuf.Empty\x1a*.shopping_list.v1.GetShoppingListsResponse\x12o\n" +
	"\x12CreateShoppingList\x12+.shopping_list.v1.CreateShoppingListRequest\x1a,.shopping_list.v1.CreateShoppingListResponse\x12o\n" +
	"\x12UpdateShoppingList\x12+.shopping_list.v1.UpdateShoppingListRequest\x1a,.shopping_list.v1.UpdateShoppingListResponse\x12o\n" +
	"\x12DeleteShoppingList\x12+.shopping_list.v1.DeleteShoppingListRequest\x1a,.shopping_list.v1.DeleteShoppingListResponse\x12f\n" +
	"\x18GetItemsByShoppingListId\x12\x16.google.protobuf.Empty\x1a2.shopping_list.v1.GetItemsByShoppingListIdResponseB\x1fZ\x1dpkg/grpc/v1/shopping_list_apib\x06proto3"

var (
	file_api_grpc_v1_shopping_list_proto_rawDescOnce sync.Once
	file_api_grpc_v1_shopping_list_proto_rawDescData []byte
)

func file_api_grpc_v1_shopping_list_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_shopping_list_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_shopping_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_shopping_list_proto_rawDesc), len(file_api_grpc_v1_shopping_list_proto_rawDesc)))
	})
	return file_api_grpc_v1_shopping_list_proto_rawDescData
}

var file_api_grpc_v1_shopping_list_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_grpc_v1_shopping_list_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_grpc_v1_shopping_list_proto_goTypes = []any{
	(State)(0),                               // 0: shopping_list.v1.State
	(*ShoppingList)(nil),                     // 1: shopping_list.v1.ShoppingList
	(*Item)(nil),                             // 2: shopping_list.v1.Item
	(*CreateShoppingListRequest)(nil),        // 3: shopping_list.v1.CreateShoppingListRequest
	(*CreateShoppingListResponse)(nil),       // 4: shopping_list.v1.CreateShoppingListResponse
	(*UpdateShoppingListRequest)(nil),        // 5: shopping_list.v1.UpdateShoppingListRequest
	(*UpdateShoppingListResponse)(nil),       // 6: shopping_list.v1.UpdateShoppingListResponse
	(*DeleteShoppingListRequest)(nil),        // 7: shopping_list.v1.DeleteShoppingListRequest
	(*DeleteShoppingListResponse)(nil),       // 8: shopping_list.v1.DeleteShoppingListResponse
	(*GetShoppingListRequest)(nil),           // 9: shopping_list.v1.GetShoppingListRequest
	(*GetShoppingListResponse)(nil),          // 10: shopping_list.v1.GetShoppingListResponse
	(*GetShoppingListsResponse)(nil),         // 11: shopping_list.v1.GetShoppingListsResponse
	(*CreateItemRequest)(nil),                // 12: shopping_list.v1.CreateItemRequest
	(*CreateItemResponse)(nil),               // 13: shopping_list.v1.CreateItemResponse
	(*UpdateItemRequest)(nil),                // 14: shopping_list.v1.UpdateItemRequest
	(*UpdateItemResponse)(nil),               // 15: shopping_list.v1.UpdateItemResponse
	(*DeleteItemRequest)(nil),                // 16: shopping_list.v1.DeleteItemRequest
	(*DeleteItemResponse)(nil),               // 17: shopping_list.v1.DeleteItemResponse
	(*GetItemsResponse)(nil),                 // 18: shopping_list.v1.GetItemsResponse
	(*GetItemRequest)(nil),                   // 19: shopping_list.v1.GetItemRequest
	(*GetItemResponse)(nil),                  // 20: shopping_list.v1.GetItemResponse
	(*GetItemsByShoppingListIdResponse)(nil), // 21: shopping_list.v1.GetItemsByShoppingListIdResponse
	(*timestamppb.Timestamp)(nil),            // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 23: google.protobuf.Empty
}
var file_api_grpc_v1_shopping_list_proto_depIdxs = []int32{
	22, // 0: shopping_list.v1.ShoppingList.CreatedAt:type_name -> google.protobuf.Timestamp
	22, // 1: shopping_list.v1.ShoppingList.UpdatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: shopping_list.v1.ShoppingList.state:type_name -> shopping_list.v1.State
	22, // 3: shopping_list.v1.Item.CreatedAt:type_name -> google.protobuf.Timestamp
	22, // 4: shopping_list.v1.Item.UpdatedAt:type_name -> google.protobuf.Timestamp
	22, // 5: shopping_list.v1.CreateShoppingListRequest.CreatedAt:type_name -> google.protobuf.Timestamp
	22, // 6: shopping_list.v1.CreateShoppingListRequest.UpdatedAt:type_name -> google.protobuf.Timestamp
	0,  // 7: shopping_list.v1.CreateShoppingListRequest.state:type_name -> shopping_list.v1.State
	1,  // 8: shopping_list.v1.CreateShoppingListResponse.shoppingList:type_name -> shopping_list.v1.ShoppingList
	22, // 9: shopping_list.v1.UpdateShoppingListRequest.CreatedAt:type_name -> google.protobuf.Timestamp
	22, // 10: shopping_list.v1.UpdateShoppingListRequest.UpdatedAt:type_name -> google.protobuf.Timestamp
	0,  // 11: shopping_list.v1.UpdateShoppingListRequest.state:type_name -> shopping_list.v1.State
	1,  // 12: shopping_list.v1.UpdateShoppingListResponse.shoppingList:type_name -> shopping_list.v1.ShoppingList
	1,  // 13: shopping_list.v1.GetShoppingListResponse.shoppingList:type_name -> shopping_list.v1.ShoppingList
	1,  // 14: shopping_list.v1.GetShoppingListsResponse.shoppingList:type_name -> shopping_list.v1.ShoppingList
	22, // 15: shopping_list.v1.CreateItemRequest.CreatedAt:type_name -> google.protobuf.Timestamp
	22, // 16: shopping_list.v1.CreateItemRequest.UpdatedAt:type_name -> google.protobuf.Timestamp
	2,  // 17: shopping_list.v1.CreateItemResponse.item:type_name -> shopping_list.v1.Item
	22, // 18: shopping_list.v1.UpdateItemRequest.CreatedAt:type_name -> google.protobuf.Timestamp
	22, // 19: shopping_list.v1.UpdateItemRequest.UpdatedAt:type_name -> google.protobuf.Timestamp
	2,  // 20: shopping_list.v1.UpdateItemResponse.item:type_name -> shopping_list.v1.Item
	2,  // 21: shopping_list.v1.GetItemsResponse.items:type_name -> shopping_list.v1.Item
	2,  // 22: shopping_list.v1.GetItemResponse.item:type_name -> shopping_list.v1.Item
	2,  // 23: shopping_list.v1.GetItemsByShoppingListIdResponse.items:type_name -> shopping_list.v1.Item
	19, // 24: shopping_list.v1.ShoppingListService.GetItem:input_type -> shopping_list.v1.GetItemRequest
	23, // 25: shopping_list.v1.ShoppingListService.GetItems:input_type -> google.protobuf.Empty
	12, // 26: shopping_list.v1.ShoppingListService.CreateItem:input_type -> shopping_list.v1.CreateItemRequest
	14, // 27: shopping_list.v1.ShoppingListService.UpdateItem:input_type -> shopping_list.v1.UpdateItemRequest
	16, // 28: shopping_list.v1.ShoppingListService.DeleteItem:input_type -> shopping_list.v1.DeleteItemRequest
	9,  // 29: shopping_list.v1.ShoppingListService.GetShoppingList:input_type -> shopping_list.v1.GetShoppingListRequest
	23, // 30: shopping_list.v1.ShoppingListService.GetShoppingLists:input_type -> google.protobuf.Empty
	3,  // 31: shopping_list.v1.ShoppingListService.CreateShoppingList:input_type -> shopping_list.v1.CreateShoppingListRequest
	5,  // 32: shopping_list.v1.ShoppingListService.UpdateShoppingList:input_type -> shopping_list.v1.UpdateShoppingListRequest
	7,  // 33: shopping_list.v1.ShoppingListService.DeleteShoppingList:input_type -> shopping_list.v1.DeleteShoppingListRequest
	23, // 34: shopping_list.v1.ShoppingListService.GetItemsByShoppingListId:input_type -> google.protobuf.Empty
	20, // 35: shopping_list.v1.ShoppingListService.GetItem:output_type -> shopping_list.v1.GetItemResponse
	18, // 36: shopping_list.v1.ShoppingListService.GetItems:output_type -> shopping_list.v1.GetItemsResponse
	13, // 37: shopping_list.v1.ShoppingListService.CreateItem:output_type -> shopping_list.v1.CreateItemResponse
	15, // 38: shopping_list.v1.ShoppingListService.UpdateItem:output_type -> shopping_list.v1.UpdateItemResponse
	17, // 39: shopping_list.v1.ShoppingListService.DeleteItem:output_type -> shopping_list.v1.DeleteItemResponse
	10, // 40: shopping_list.v1.ShoppingListService.GetShoppingList:output_type -> shopping_list.v1.GetShoppingListResponse
	11, // 41: shopping_list.v1.ShoppingListService.GetShoppingLists:output_type -> shopping_list.v1.GetShoppingListsResponse
	4,  // 42: shopping_list.v1.ShoppingListService.CreateShoppingList:output_type -> shopping_list.v1.CreateShoppingListResponse
	6,  // 43: shopping_list.v1.ShoppingListService.UpdateShoppingList:output_type -> shopping_list.v1.UpdateShoppingListResponse
	8,  // 44: shopping_list.v1.ShoppingListService.DeleteShoppingList:output_type -> shopping_list.v1.DeleteShoppingListResponse
	21, // 45: shopping_list.v1.ShoppingListService.GetItemsByShoppingListId:output_type -> shopping_list.v1.GetItemsByShoppingListIdResponse
	35, // [35:46] is the sub-list for method output_type
	24, // [24:35] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_shopping_list_proto_init() }
func file_api_grpc_v1_shopping_list_proto_init() {
	if File_api_grpc_v1_shopping_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_shopping_list_proto_rawDesc), len(file_api_grpc_v1_shopping_list_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_shopping_list_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_shopping_list_proto_depIdxs,
		EnumInfos:         file_api_grpc_v1_shopping_list_proto_enumTypes,
		MessageInfos:      file_api_grpc_v1_shopping_list_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_shopping_list_proto = out.File
	file_api_grpc_v1_shopping_list_proto_goTypes = nil
	file_api_grpc_v1_shopping_list_proto_depIdxs = nil
}
